---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/netavark.spec
upstream_tag_template: v{version}

srpm_build_deps:
  - cargo
  - make
  - openssl-devel

jobs:
  - job: copr_build
    trigger: pull_request
    notifications:
      failure_comment:
        message: "Ephemeral COPR build failed. @containers/packit-build please check."
    enable_net: true
    targets:
      - fedora-all-x86_64
      - fedora-all-aarch64
      - centos-stream+epel-next-8-x86_64
      - centos-stream+epel-next-8-aarch64
      - centos-stream+epel-next-9-x86_64
      - centos-stream+epel-next-9-aarch64
    additional_repos:
      - "copr://rhcontainerbot/podman-next"

  # Run on commit to main branch
  - job: copr_build
    trigger: commit
    notifications:
      failure_comment:
        message: "podman-next COPR build failed. @containers/packit-build please check."
    branch: main
    owner: rhcontainerbot
    project: podman-next
    enable_net: true

  - job: propose_downstream
    trigger: release
    update_release: false
    dist_git_branches:
      - fedora-all

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all

        # NOTE: Bodhi update tasks are disabled to allow netavark and aardvark-dns X.Y
        # builds in a single manual bodhi update. Leaving this commented out
        # but not deleted so it's not forgotten.
        #- job: bodhi_update
        #trigger: commit
        #dist_git_branches:
        #- fedora-branched # rawhide updates are created automatically
